name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build
      run: mkdir -p build
    - run: cmake -B build -S .
    - run: make -C build/
    - name: unittest
      run: ./build/unittest
